
language: c
  
os:
  - linux

compiler:
  - gcc
  
before_script:
  - sudo bash build/Linux-Build.sh -c

script:
  - cd build/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash Linux-Build.sh x86 -i; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash Linux-Build.sh x64 -i; fi